- filename: everywhere.jpg
  short_name: везде
  url: https://pbs.twimg.com/media/D_1pEiZUYAIxzkG.jpg
  full_url: https://i3.imageban.ru/out/2021/04/21/6b8a3cda19977102667b40a4a416a9f8.jpg
  texts:
  - color:
    - 255
    - 255
    - 255
    position:
    - 250
    - 15
    ratio:
    - 4
    - 1
    size_cap:
    - 520
    - 130
- filename: hug_behind.jpg
  short_name: приподнял
  url: https://imgflip.com/s/meme/Running-Away-Balloon.jpg
  full_url: https://i2.imageban.ru/out/2021/04/21/5a9dad1af029c775d0be0d80a1e25160.jpg
  texts:
  - color:
    - 0
    - 0
    - 0
    position:
    - 220
    - 65
    ratio:
    - 1
    - 1
    size_cap:
    - 120
    - 120
  - color:
    - 0
    - 0
    - 0
    position:
    - 20
    - 350
    ratio:
    - 1
    - 1
    size_cap:
    - 100
    - 90
- filename: nordic_gamer.jpg
  short_name: геймер
  url: https://medialeaks.ru/wp-content/uploads/2020/08/annotacziya-2020-08-04-154532-768x719.jpg
  full_url: https://i4.imageban.ru/out/2021/04/21/b0bd6c94e553f888841241a3497167bc.jpg
  texts:
  - color:
    - 0
    - 0
    - 0
    position:
    - 15
    - 220
    ratio:
    - 2
    - 1
    size_cap:
    - 200
    - 100
  - color:
    - 0
    - 0
    - 0
    position:
    - 400
    - 220
    ratio:
    - 2
    - 1
    size_cap:
    - 180
    - 100
  - color:
    - 0
    - 0
    - 0
    position:
    - 15
    - 520
    ratio:
    - 2
    - 1
    size_cap:
    - 200
    - 100
  - color:
    - 0
    - 0
    - 0
    position:
    - 400
    - 520
    ratio:
    - 2
    - 1
    size_cap:
    - 180
    - 100
- filename: shit.jpg
  short_name: дерьмо
  url: https://i.imgflip.com/17811q.jpg
  full_url: https://i2.imageban.ru/out/2021/04/21/5cb18bc699045fe0db2e35f7cdfb4dc0.jpg
  texts:
  - color:
    - 0
    - 0
    - 0
    position:
    - 95
    - 450
    ratio:
    - 3
    - 1
    size_cap:
    - 210
    - 55
- filename: what_hour.jpg
  short_name: который_час
  url: https://i.pinimg.com/originals/7f/3f/48/7f3f48d2134a47cdef72784ce21492d9.jpg
  full_url: https://i3.imageban.ru/out/2021/04/21/137433b47a46ab3ae2b4811c18c18c14.jpg
  texts:
  - color:
    - 0
    - 0
    - 0
    font: Roboto-Bold.ttf
    position:
    - 600
    - 170
    ratio:
    - 1
    - 1
    size_cap:
    - 130
    - 130
- filename: brain.jpg
  short_name: мозг
  url: https://www.meme-arsenal.com/memes/c268f44cc5dff81dd84453e9225deb10.jpg
  full_url: https://i2.imageban.ru/out/2021/04/21/ef7ad69ef6d9d3e1e5ad0e5852eb3e52.jpg
  texts:
  - color:
    - 0
    - 0
    - 0
    position:
    - 20
    - 20
    ratio:
    - 1
    - 1
    size_cap:
    - 300
    - 225
  - color:
    - 0
    - 0
    - 0
    position:
    - 20
    - 260
    ratio:
    - 1
    - 1
    size_cap:
    - 300
    - 225
  - color:
    - 0
    - 0
    - 0
    position:
    - 20
    - 500
    ratio:
    - 1
    - 1
    size_cap:
    - 300
    - 225
  - color:
    - 0
    - 0
    - 0
    position:
    - 20
    - 735
    ratio:
    - 1
    - 1
    size_cap:
    - 300
    - 225

- filename: smart.jpg
  short_name: умник
  url: https://www.meme-arsenal.com/memes/5042c98088afd9b9a11a9f71e8f05681.jpg
  full_url: https://i6.imageban.ru/out/2021/04/21/8dbc9df69a8340839b9ed89e3ac932db.jpg
  texts:
  - color:
    - 255
    - 255
    - 255
    position:
    - 245
    - 70
    ratio:
    - 4
    - 1
    size_cap:
    - 690
    - 135
- filename: fire.jpg
  short_name: огонь
  url: https://i6.imageban.ru/out/2021/04/21/5ba90018118d676bfc6c486f66f17695.png
  full_url: https://i6.imageban.ru/out/2021/04/21/5ba90018118d676bfc6c486f66f17695.png
  texts:
  - color:
    - 255
    - 255
    - 255
    position:
    - 160
    - 370
    ratio:
    - 4
    - 1
    size_cap:
    - 400
    - 130
- filename: sceptic.jpg
  short_name: скептик
  url: https://i5.imageban.ru/out/2021/04/21/831fe50147a3ae6436b377b30365613f.png
  full_url: https://i5.imageban.ru/out/2021/04/21/831fe50147a3ae6436b377b30365613f.png
  texts:
  - color:
    - 255
    - 255
    - 255
    position:
    - 160
    - 330
    ratio:
    - 4
    - 1
    size_cap:
    - 400
    - 130
- filename: what.jpg
  short_name: что
  url: https://i1.imageban.ru/out/2021/04/21/8cddf0b4e951325282555f2334f04639.png
  full_url: https://i1.imageban.ru/out/2021/04/21/8cddf0b4e951325282555f2334f04639.png
  texts:
  - color:
    - 255
    - 255
    - 255
    position:
    - 160
    - 330
    ratio:
    - 4
    - 1
    size_cap:
    - 400
    - 130
- filename: is_this.jpg
  short_name: это_мем
  url: https://i5.imageban.ru/out/2021/04/21/d7d459bfb4842f20e47d8338fa429cbf.jpg
  full_url: https://i5.imageban.ru/out/2021/04/21/d7d459bfb4842f20e47d8338fa429cbf.jpg
  texts:
  - color:
    - 255
    - 255
    - 255
    position:
    - 1150
    - 190
    ratio:
    - 1
    - 1
    size_cap:
    - 350
    - 350
  - color:
    - 255
    - 255
    - 255
    position:
    - 300
    - 1250
    ratio:
    - 5
    - 1
    size_cap:
    - 990
    - 200
- filename: sad_cat.jpg
  short_name: грустнокотики
  url: https://i2.imageban.ru/out/2021/04/26/e880b77c52e40309a4ea00fa58d769dd.jpeg
  full_url: https://i2.imageban.ru/out/2021/04/26/e880b77c52e40309a4ea00fa58d769dd.jpeg
  texts:
  - color:
    - 0
    - 0
    - 0
    position:
    - 65
    - 450
    ratio:
    - 3
    - 1
    size_cap:
    - 330
    - 90
  - color:
    - 0
    - 0
    - 0
    position:
    - 650
    - 450
    ratio:
    - 3
    - 1
    size_cap:
    - 330
    - 90
- filename: commi_rabbit.jpg
  short_name: commi_rabbit
  url: https://i5.imageban.ru/out/2021/05/12/35fa1fbb1fa74da76e37bf6aa2a5b1b2.jpeg
  full_url: https://i5.imageban.ru/out/2021/05/12/35fa1fbb1fa74da76e37bf6aa2a5b1b2.jpeg
  texts:
  - color: [255, 255, 255]
    position: [240, 80]
    ratio: [5, 1]
    size_cap: [750, 100]
  - color: [255, 255, 255]
    position: [180, 550]
    ratio: [7, 1]
    size_cap: [900, 100]

- filename: anakin.jpg
  short_name: anakin
  url: https://i3.imageban.ru/out/2021/06/25/ed1235bf19ff50be9d994e0cb97cf688.jpeg
  full_url: https://i3.imageban.ru/out/2021/06/25/ed1235bf19ff50be9d994e0cb97cf688.jpeg
  texts:
  - color: [255, 255, 255]
    position: [20, 250]
    ratio: [5, 1]
    size_cap: [275, 65]
  - color: [255, 255, 255]
    position: [350, 250]
    ratio: [5, 1]
    size_cap: [275, 65]
  - color: [255, 255, 255]
    position: [350, 580]
    ratio: [5, 1]
    size_cap: [275, 65]